Repository Hochfrequenz/intermediate-bo4e-migration-models, pull requests merged in 2023-10, with the labels that each got.

#64 Add aggregationsverantwortung to bilanzierung
  src/ibims/bo/bilanzierung.py
  src/ibims/enum/aggregationsverantwortung.py
Labels: enhancement

#73 add default for aggregationsverantwortung
  src/ibims/bo/bilanzierung.py
Labels: bug

#72 Add workflow to auto-approve and -merge dependabot PRs
  .github/workflows/dependabot_automerge.yml
Labels: dependencies

#75 add prognosegrundlage to bilanzierung
  src/ibims/bo/bilanzierung.py
Labels: enhancement
